OHJEET = {
    "Ohje imusolmukenäytteenottoa varten": (
        "### Ohje imusolmukenäytteenottoa varten\n\n"
        "Lymfoomaa epäiltäessä pyyntö histologiseen tutkimukseen laaditaan aina kiireellisenä. Pyynnössä vaadittavat asiat:\n\n"
        "* Mistä näyte on otettu\n"
        "* Minkälaisia oireita potilaalla on\n"
        "* Mikä on kliinikon diagnoosiepäily\n"
        "* Onko potilaalla aiemmin todettuja syöpiä\n"
        "* Mahdolliset verenkuvan muutokset\n"
        "* Kuvantamislöydökset (erityisesti suurentunut perna)\n"
        "* Oleelliset perussairaudet (kuten mahdolliset immuunipuutokseen liittyvät sairaudet sekä erityisesti keliakia ohutsuolikasvaimen yhteydessä)\n"
        "* Jos lähettävä yksikkö on lähettänyt materiaalia suoraan genetiikalle ja kliinisen kemian hematologialle, se on mainittava lähetteessä.\n\n"
        "Morfologinen tutkimus perustuu lymfoomasolujen tunnistamisen lisäksi koko imusolmukkeen yleisrakenteen ja kasvainsolujen mikroympäristön arviointiin. Siksi lymfoomaa epäiltäessä tulisi aina pyrkiä poistamaan kokonainen imusolmuke kapseleineen tai ottamaan muu, runsas kirurginen näyte. Ohutneulanäytteellä voidaan sulkea pois karsinooma, mutta se ei sovellu lymfoomadiagnostiikkaan. Paksuneulanäyte (KNB) ei myöskään ole useinkaan riittävä. KNB:aa suositellaan ainoastaan tietyissä erityistapauksissa, kuten mediastinaalisissa tai abdominaalisissa tuumoreissa, mikäli hoito on aloitettava päivystysluonteisesti tai kohde on hankala biopsioida.\n\n"
        "Optimaalinen näytteenottokohta on ensisijaisesti suurin epänormaalilta vaikuttava imusolmuke. Histopatologiselta kannalta suositeltavimpia ovat kaulan alueen imusolmukkeet. Nivusimusolmukkeita on vältettävä, ellei tauti kohdistu nimenomaan niihin.\n\n"
        "Ilta- ja viikonloppuaikoina sekä juhlapyhinä puolet näytteestä voidaan kiinnittää formaliiniin ja puolet säilyttää elatusnesteessä (tai fysiologisessa suolaliuoksessa) jääkaapissa.\n\n"
        "Perna, joka poistetaan veritaudin takia, olisi syytä toimittaa tuoreena. Jos näytettä ei pystytä lähettämään tuoreena, toimenpiteen suorittanut lääkäri halkaisee sen ja asettaa formaliiniin.\n\n"
        "**Lymfoomadiagnostiikassa välttämättömiä ovat:**\n\n"
        "* **4049 Ln-PAD**; näytemäärä minimi 1 cm³\n"
        "  * fiksoidaan formaliiniin: formaliinia sisältävä tiiviskantinen näyteastia\n"
        "  * Tarra: Kudosnäyte, 10 % formaliini\n"
        "  * Formaliinin tilavuuden on oltava kymmenkertainen näytepalaan verrattuna.\n"
        "* **3746 Ts-Lmark** = pinta-antigeeni; näytemäärä 0,5 cm³ (jos kudosnäytettä on niukasti, suositellaan ensisijaisesti otettavaksi kudosnäyte pinta-antigeenitutkimusta varten)\n"
        "  * toimitetaan välittömästi kliinisen hematologian laboratorioon\n"
        "  * jos näyte otetaan perjantaina tai arkipyhän aattona, tulee näyte ottaa ennen klo 13 ja ilmoittaa hematologian laboratorioon\n"
        "* Tarvittaessa kliinikon pyynnöstä tehdään suuntaa antava jääleike.\n"
        "* Jos näytemateriaalia on runsaasti, pyydetään myös **4552 Ts-Kromhem** = kromosomi; näytemäärä 1 cm³ steriiliin ravintonesteputkeen (9 ml vakuumiputki, no additive, tilataan genetiikan laboratoriosta)\n"
        "  * toimitetaan kliinisen genetiikan laboratorioon huoneenlämpöisenä mahdollisimman nopeasti\n"
    )
}