OHJEET = {
    "Ohje imusolmukenäytteenottoa varten": (
        "### Ohje imusolmukenäytteenottoa varten\n\n"
        "Lymfoomaa epäiltäessä pyyntö histologiseen tutkimukseen laaditaan aina kiireellisenä. Pyynnössä vaadittavat asiat:\n\n"
        "* Mistä näyte on otettu\n"
        "* Minkälaisia oireita potilaalla on\n"
        "* Mikä on kliinikon diagnoosiepäily\n"
        "* Onko potilaalla aiemmin todettuja syöpiä\n"
        "* Mahdolliset verenkuvan muutokset\n"
        "* Kuvantamislöydökset (erityisesti suurentunut perna)\n"
        "* Oleelliset perussairaudet (kuten mahdolliset immuunipuutokseen liittyvät sairaudet sekä erityisesti keliakia ohutsuolikasvaimen yhteydessä)\n"
        "* Jos lähettävä yksikkö on lähettänyt materiaalia suoraan genetiikalle ja kliinisen kemian hematologialle, se on mainittava lähetteessä.\n\n"
        "Morfologinen tutkimus perustuu lymfoomasolujen tunnistamisen lisäksi koko imusolmukkeen yleisrakenteen ja kasvainsolujen mikroympäristön arviointiin. Siksi lymfoomaa epäiltäessä tulisi aina pyrkiä poistamaan kokonainen imusolmuke kapseleineen tai ottamaan muu, runsas kirurginen näyte. Ohutneulanäytteellä voidaan sulkea pois karsinooma, mutta se ei sovellu lymfoomadiagnostiikkaan. Paksuneulanäyte (KNB) ei myöskään ole useinkaan riittävä. KNB:aa suositellaan ainoastaan tietyissä erityistapauksissa, kuten mediastinaalisissa tai abdominaalisissa tuumoreissa, mikäli hoito on aloitettava päivystysluonteisesti tai kohde on hankala biopsioida.\n\n"
        "Optimaalinen näytteenottokohta on ensisijaisesti suurin epänormaalilta vaikuttava imusolmuke. Histopatologiselta kannalta suositeltavimpia ovat kaulan alueen imusolmukkeet. Nivusimusolmukkeita on vältettävä, ellei tauti kohdistu nimenomaan niihin.\n\n"
        "Ilta- ja viikonloppuaikoina sekä juhlapyhinä puolet näytteestä voidaan kiinnittää formaliiniin ja puolet säilyttää elatusnesteessä (tai fysiologisessa suolaliuoksessa) jääkaapissa.\n\n"
        "Perna, joka poistetaan veritaudin takia, olisi syytä toimittaa tuoreena. Jos näytettä ei pystytä lähettämään tuoreena, toimenpiteen suorittanut lääkäri halkaisee sen ja asettaa formaliiniin.\n\n"
        "**Lymfoomadiagnostiikassa välttämättömiä ovat:**\n\n"
        "* **4049 Ln-PAD**; näytemäärä minimi 1 cm³\n"
        "  * fiksoidaan formaliiniin: formaliinia sisältävä tiiviskantinen näyteastia\n"
        "  * Tarra: Kudosnäyte, 10 % formaliini\n"
        "  * Formaliinin tilavuuden on oltava kymmenkertainen näytepalaan verrattuna.\n"
        "* **3746 Ts-Lmark** = pinta-antigeeni; näytemäärä 0,5 cm³ (jos kudosnäytettä on niukasti, suositellaan ensisijaisesti otettavaksi kudosnäyte pinta-antigeenitutkimusta varten)\n"
        "  * toimitetaan välittömästi kliinisen hematologian laboratorioon\n"
        "  * jos näyte otetaan perjantaina tai arkipyhän aattona, tulee näyte ottaa ennen klo 13 ja ilmoittaa hematologian laboratorioon\n"
        "* Tarvittaessa kliinikon pyynnöstä tehdään suuntaa antava jääleike.\n"
        "* Jos näytemateriaalia on runsaasti, pyydetään myös **4552 Ts-Kromhem** = kromosomi; näytemäärä 1 cm³ steriiliin ravintonesteputkeen (9 ml vakuumiputki, no additive, tilataan genetiikan laboratoriosta)\n"
        "  * toimitetaan kliinisen genetiikan laboratorioon huoneenlämpöisenä mahdollisimman nopeasti\n"
    ),
    "Aggressiivisten lymfoomien seuranta": (
        "### Aggressiivisten lymfoomien seuranta\n\n"
        "*(LBCL, T-soluiset, aivolymfooma (ei-kantasolusiirron saaneet) — Kantasolusiirron saaneilla kts. kohta \"Kantasolusiirtopotilaat\")*\n\n"
        "**EOT 1kk (End of Treatment)**\n"
        "* LVO (Lääkärin vastaanotto)\n"
        "* Vartalon ja kaulan TT ja tarv. PET-TT, aivolymfooma: pään MRI\n"
        "* Lab: TVK, krea, ALAT, bil\n"
        "* Jos antibiootiprofylaksia CD4\n\n"
        "**1. vuosi**\n"
        "* LVO 3 kk\n"
        "* LVO:t jatkuvat lääkärin arvion mukaan 6 ja 12kk (esim. jos hoidoista toipuminen kesken)\n"
        "* Stabiilissa tilanteessa siirto DHP/lymf.hoitajan vo (6 ja 12 kk)\n"
        "* Vartalon ja kaulan TT 11 kk, jos potilas on CAR-T-solukandidaatti/CART indikaatio\n"
        "* Lab: TSH ja T4v 12kk, jos sädehoito kaulan alueelle, muuten ei rutiininomaista lab.seurantaa KYS\n\n"
        "**2. vuosi**\n"
        "* LVO/lymf.hoitajan vo/DHP seurantakysely 18 ja 24kk\n"
        "* Ei rutiininomaista kuvantamisseurantaa\n"
        "* Lab: 24 kk ohjeistetaan avoterveydenhuoltoon PVK+t, HbA1c, kolesteroli- ja D-vit status\n\n"
        "**3–5 vuotta**\n"
        "* Lymf.hoitajan vo/DHP seurantakysely 36, 48 ja 60 kk\n"
        "* Lab: 60 kk ohjeistataan avoterveydenhuoltoon PVK+t, HbA1c, kolesteroli- ja D-vit status\n\n"
        "**6–10 vuotta**\n"
        "* Ei rutiiniseurantaa\n"
        "* Yhteydenottomahdollisuus lymf.hoitajan/DHP auki ad 10 v\n"
    ),
    "Indolenttien lymfoomien seuranta": (
        "### Indolenttien lymfoomien seuranta (hoidetut)\n\n"
        "*(Follikulaarinen, MALT, MZL, NLPHL, mantteli (jos ei 1L ASCT, eikä ole ylläpitohoidoissa))*\n\n"
        "**EOT 1kk (End of Treatment)**\n"
        "* LVO (Lääkärin vastaanotto)\n"
        "* Vartalon ja kaulan TT ja tarv. PET-TT\n"
        "* Lab: TVK, krea, ALAT, bil\n"
        "* Jos antibiootiprofylaksia Ly-CD4\n\n"
        "**1. vuosi**\n"
        "* LVO 3 kk\n"
        "* LVO:t jatkuvat lääkärin arvion mukaan 6 ja 12kk (esim. jos hoidoista toipuminen kesken)\n"
        "* Stabiilissa tilanteessa siirto DHP/lymf.hoitajan vo (6 ja 12 kk), mutta ylläpitohoito LVO:lla\n"
        "* Ei rutiininomaista lab.seurantaa KYS\n\n"
        "**2. vuosi**\n"
        "* Ylläpitohoidossa olevat LVO:lla 18 kk\n"
        "* Lymf.hoitajan vo/DHP seurantakysely 18 ja 24kk\n"
        "* Vartalon ja kaulan TT 18kk FL, MZL, MCL\n"
        "* Lab: 24 kk ohjeistataan avoterveydenhuoltoon PVK+t, HbA1c, kolesteroli- ja D-vit status sytostaattia saaneille\n\n"
        "**3–5 vuotta**\n"
        "* Lymf.hoitajan vo/DHP seurantakysely 36, 48 ja 60 kk\n"
        "* Lab: 60 kk ohjeistataan avoterveydenhuoltoon PVK+t, HbA1c, kolesteroli- ja D-vit status sytostaattia saaneille\n\n"
        "**6–10 vuotta**\n"
        "* Ei rutiiniseurantaa\n"
        "* Yhteydenottomahdollisuus lymf.hoitajan/DHP auki ad 10 v\n"
    ),
    "Indolentti lymfooma - aktiivinen seuranta": (
        "### Indolentti lymfooma — aktiivinen seuranta\n\n"
        "**EOT 1kk**\n"
        "* LVO\n"
        "* Vartalon ja kaulan TT 3–6kk, 12kk tautitaakan ja kliinisen kuvan mukaan\n"
        "* Lymfooma lab\n\n"
        "**2. vuosi**\n"
        "* LVO 24kk\n"
        "* Vartalon ja kaulan TT, lymfooma lab\n\n"
        "**3–5 vuotta**\n"
        "* Lymf.hoitajan vo/DHP\n"
        "* Jos leukeeminen tauti, TVK 6kk välein\n\n"
        "**6–10 vuotta**\n"
        "* Ei rutiiniseurantaa\n"
        "* Yhteydenottomahdollisuus lymf.hoitajan/DHP auki ad 10 v\n"
        "* Leukeemisessa taudissa TVK-tarkistus 1v välein ad 10v\n"
    ),
    "Klassinen Hodgkinin lymfooma": (
        "### Klassinen Hodgkinin lymfooma - seuranta\n\n"
        "**EOT 1kk**\n"
        "* LVO\n"
        "* Vartalon ja kaulan TT ja PET-TT\n"
        "* Lab: TVK, krea, ALAT, bil\n"
        "* Jos antibiootiprofylaksia, Ly-CD4\n\n"
        "**1. vuosi**\n"
        "* LVO 3 kk\n"
        "* LVO:t jatkuvat lääkärin arvion mukaan 6 ja 12kk (esim. jos hoidoista toipuminen kesken)\n"
        "* Stabiilissa tilanteessa siirto DHP/lymf.hoitajan vo (6 ja 12 kk)\n"
        "* Lab: TSH ja T4v 12kk, jos sädehoito (rt) kaulan alueelle\n\n"
        "**2. vuosi**\n"
        "* LVO/lymf.hoitajan vo/DHP seurantakysely 18 ja 24kk\n"
        "* Ei rutiinikuvantamisia\n"
        "* Lab: TSH ja T4v 24kk, jos rt kaulan alueelle; 24 kk PVK+t, HbA1c, kolesteroli- ja D-vit\n\n"
        "**3–5 vuotta**\n"
        "* Lymf.hoitajan vo/DHP seurantakysely 36, 48 ja 60 kk\n"
        "* Lab: TSH ja T4v 36, 48 ja 60 kk, jos rt kaulan alueelle; 60 kk ohjeistataan avoterveydenhuoltoon PVK+t, HbA1c, kolesteroli- ja D-vit status\n\n"
        "**6–10 vuotta**\n"
        "* Ei rutiiniseurantaa\n"
        "* Yhteydenottomahdollisuus lymf.hoitajan/DHP auki ad 10 v\n"
        "* Jos saanut rintojen alueelle sädehoidon >10 Gy ≤ 30v iässä: rintojen MRI vuosittain 25 v. iästä alkaen, mutta aikaisintaan 96 kk hoitojen päättymisestä ad 59v, 35 v. iästä alkaen myös mammografia vuosittain ad 70 v. Sen jälkeen mammografia joka toinen vuosi niin kauan kuin katsotaan hoitokuntoiseksi.\n"
        "* Lab.kokeet: TSH ja T4v 72, 84, 96, 108, 120 kk, jos rt kaulan alueelle\n"
    ),
    "Kantasolusiirtopotilaat": (
        "### Kantasolusiirtopotilaat - seuranta\n\n"
        "*(Allogeenisen siirron jälkeen siirtokeskuksen ohjeen mukaan)*\n\n"
        "**EOT 1kk**\n"
        "* LVO\n"
        "* Lab: TVK, krea, ALAT, bil, Ly-CD4, S-IgG\n\n"
        "**1. vuosi**\n"
        "* LVO 3, 6 ja 12 kk; jos toipumisessa ongelmia, tarv. tiheämmin\n"
        "* Rokotusten ohjelmointi\n"
        "* Vartalon ja kaulan TT, tarv. PET-TT 3kk; aivolymfoomassa pään MRI\n"
        "* Lab LVO yht: PVK+n, krea, ALAT, bil, Ly-CD4, S-IgG, kunnes korjaantuneet\n\n"
        "**2. vuosi**\n"
        "* LVO/lymf.hoitajan vo/DHP seurantakysely 18 ja 24kk\n"
        "* Ei rutiinikuvantamisia\n"
        "* Lab 24kk: PVK+t, HbA1c, kolesteroli- ja D-vit status\n\n"
        "**3–5 vuotta**\n"
        "* Lymf.hoitajan vo/DHP seurantakysely 36, 48 ja 60 kk\n"
        "* Lab 60 kk: PVK+t, krea, ALAT, bil sekä PVK+t, HbA1c, kolesteroli- ja D-vit status\n\n"
        "**6–10 vuotta**\n"
        "* Ei rutiiniseurantaa\n"
        "* Yhteydenottomahdollisuus lymf.hoitajan/DHP auki ad 10 v\n"
    ),
    "CAR-T tai BiTE-hoitoja saaneet potilaat": (
        "### CAR-T-soluhoitoja tai BiTE-hoitoja saaneet potilaat - seuranta\n\n"
        "*(huomioi myös siirtokeskuksen ohjeet)*\n\n"
        "**EOT 1kk**\n"
        "* LVO\n"
        "* Lab: TVK, krea, ALAT, bil, Ly-CD4, S-IgG\n\n"
        "**1. vuosi**\n"
        "* LVO 3, 6 ja 12 kk\n"
        "* PET-TT 3 kk\n"
        "* Lab LVO yht: PVK+n, lymfosyyttidiff, krea, ALAT, bil, Ly-CD4 sekä S-IgG, kunnes korjaantuneet\n\n"
        "**2. vuosi**\n"
        "* LVO 18 ja 24kk\n"
        "* Ei rutiinikuvantamisia\n"
        "* Lab LVO yht: PVK+n, lymfosyyttidiff, krea, ALAT, bil, sekä S-IgG, kunnes korjaantuneet\n"
        "* 24kk HbA1c, kolesteroli- ja D-vit status\n\n"
        "**3–5 vuotta**\n"
        "* LVO 36 kk (tarvittaessa pidempään)\n"
        "* Lab LVO yht: PVK+n, lymfosyyttidiff, krea, ALAT, bil, sekä S-IgG, kunnes korjaantuneet\n"
        "* Lab 60 kk: PVK+t, krea, ALAT, bil sekä PVK+t, HbA1c, kolesteroli- ja D-vit status\n"
        "* Jos ei ongelmia, 48kk alkaen kuten kantasolusiirtopotilaat\n"
    )
}